default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY'],
      is_key_content_base64: true
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: '../src-tauri/gen/apple/build/arm64/swaptun.ipa',
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end

  desc "Upload to App Store"
  lane :production do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY'],
      is_key_content_base64: true
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: '../src-tauri/gen/apple/build/arm64/swaptun.ipa',
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      automatic_release: false
    )
  end
end
